### ISSUE TITLE
if __name__ == "__main__":

### ISSUE THREAD

**Issue by ecoppen** [mmmahiii/Programming-Challenges#5]
https://github.com/mmmahiii/Programming-Challenges/blob/4ad5043976b9f769e9fdb125815d3fc5ec8ce664/2-%20Richter/2-%20Richter.py#L31

```
if __name__ == "__main__":
    main() 
```

**Comment by mmmahiii** [comment]
Sir whats the reason for this improvement because just ' main() ' works

**Comment by ecoppen** [comment]
Indeed it does, however when you `import` this program into another program, it'll automatically run the code which isn't the desired outcome. As explained in class you need to start getting used to writing programs in a way that they can be automatically tested.

To understand this you need to do a few things:

1. Rename `2- Richter.py` to `richter.py`
2. Create `testing.py` in the same folder as `richter.py` with the following code:
```
import unittest

from richter import *


class MyFirstTests(unittest.TestCase):

    def test_convertJoules(self):
        self.assertEqual(convertJoules(1), 1995262.314968789)


if __name__ == '__main__':
    unittest.main()
```
3. Run `testing.py` - you'll see that it'll run all of this code:
https://github.com/mmmahiii/Programming-Challenges/blob/4ad5043976b9f769e9fdb125815d3fc5ec8ce664/2-%20Richter/2-%20Richter.py#L23-L31

4. Change `richter.py` to have:
```
if __name__ == "__main__":
    main()
 ```
and then re-run `testing.py` - you'll see that it no longer runs the code from point 3 above. If you run `richter.py` you'll see that it runs as normal - because it's the main program and not an imported one.
